baseurl = "/"
title = "KubeVirt Basics Training"

enableGitInfo = true

languageCode = "en-us"

contentDir = "content/en"

[minify]
disableSVG = true

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[Languages]
[Languages.en]
title = "KubeVirt Basics Training"
languageName = "English"
weight = 1

# navigation
[Languages.en.menu]

[[Languages.en.menu.main]]
weight = 10
name = "acend gmbh"
url = "https://www.acend.ch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "tango"
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

[params]
copyright = "acend gmbh"
github_repo = "https://github.com/acend/kubevirt-basics-training"
github_branch = "main"

automaticSectionNumbers = true
enabledModule = "base"

# Enable Lunr.js offline search
offlineSearch = true

# kubevirt lab variables
projecthome = "/home/project"
labsfoldername = "labs"
labsubfolderprefix = "lab"
maxlabnumber = 7

end-of-lab-title = "Cleaning up resources"
end-of-lab-text = "You have reached the end of this lab. Please stop your running virtual machines to save resources on the Kubernetes cluster."

# Cloud-init - Fedora Cloud
#fedoraCloudCDI = "kubevirt/fedora-cloud-container-disk-demo:latest" # fedora cloud 32
fedoraCloudCDI = "quay.io/containerdisks/fedora:40"

# Ignition - Fedora CoreOS
fedoraCoreOSCDI = "quay.io/fedora/fedora-coreos-kubevirt:stable"
ignitionVersion = "3.4.0"

cirrosCDI = "quay.io/kubevirt/cirros-container-disk-demo"
cirrosContainerDiskDownload = "https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img"
alpineContainerDiskDownload = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/cloud/nocloud_alpine-3.20.2-x86_64-bios-cloudinit-r0.qcow2"

dummypwd = "changeme"

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to false to disable the About link in the site footer
footer_about_enable = false

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/kubevirt-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/acendch"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/acendch/"


[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  # replacements = "github.com/acend/docsy-plus -> ../../docsy-plus"
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/acend/docsy-acend"
    disable = false
  [[module.imports]]
    path = "github.com/acend/docsy-plus"
    disable = false
